# Generated by Django 4.2.6 on 2023-10-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.IntegerField()),
                ('exp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser', models.IntegerField()),
                ('name', models.TextField(default='UNKNOWN')),
                ('fn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kkm.fn')),
            ],
        ),
    ]
