# Generated by Django 4.2.6 on 2023-10-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0002_alter_kkm_fn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkm',
            name='fn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kkm.fn'),
        ),
    ]
