# Generated by Django 4.2.6 on 2023-10-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkm', '0003_alter_kkm_fn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fn',
            options={'verbose_name_plural': 'ФН'},
        ),
        migrations.AlterModelOptions(
            name='kkm',
            options={'verbose_name_plural': 'ККМ'},
        ),
        migrations.AlterField(
            model_name='fn',
            name='exp',
            field=models.DateField(verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='fn',
            name='reg',
            field=models.IntegerField(verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='fn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kkm.fn', verbose_name='Фискальный накопитель'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='name',
            field=models.TextField(default='UNKNOWN', verbose_name='Имя компьютера'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='ser',
            field=models.IntegerField(verbose_name='Серийный номер'),
        ),
    ]
